### ISSUE TITLE
"Sorry, my bot code is having an issue." on https://contososcubabot.azurewebsites.net/

### ISSUE THREAD

**Issue by IntranetFactory** [matthidinger/ContosoScubaBot#10]
Type:
i go

and get a carousel of locations.

Click on the "This one" button

an answer card is shown.

Click again on "This one" button 

result: "Sorry, my bot code is having an issue."

expected: if the user already clicked on a button, it should not be possible to click the button again.

it should be possible to update the card shown with the Action.Submit response e.g. remove buttons, show confirmation

**Comment by EricDahlvang** [comment]
Hi @IntranetFactory 

Sorry for the late response.  The current scuba bot is here now: https://contososcubademo.azurewebsites.net/
