### ISSUE TITLE
Display 1 card at at time in Carousel

### ISSUE THREAD

**Issue by PKaur1** [matthidinger/ContosoScubaBot#14]
Is there a way to implement horizontal carousel that displays 1 card at at time? I want to show only 1 card at a time in the webchat window. Currently it displays all the cards at the same time that fit into the webchat window.

**Comment by EricDahlvang** [comment]
I think you would need to fork the webchat control, and modify the internals: https://github.com/Microsoft/BotFramework-WebChat
